// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ArticleLandingPageModuleScssNamespace {
    export interface IArticleLandingPageModuleScss {
        content: string;
        noteList: string;
    }
}

declare const ArticleLandingPageModuleScssModule: ArticleLandingPageModuleScssNamespace.IArticleLandingPageModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ArticleLandingPageModuleScssNamespace.IArticleLandingPageModuleScss;
};

export = ArticleLandingPageModuleScssModule;
