// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ErrorPageModuleScssNamespace {
    export interface IErrorPageModuleScss {
        divErrorPage: string;
    }
}

declare const ErrorPageModuleScssModule: ErrorPageModuleScssNamespace.IErrorPageModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ErrorPageModuleScssNamespace.IErrorPageModuleScss;
};

export = ErrorPageModuleScssModule;
