// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ContentDemoModuleScssNamespace {
    export interface IContentDemoModuleScss {
        contentLayout: string;
    }
}

declare const ContentDemoModuleScssModule: ContentDemoModuleScssNamespace.IContentDemoModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ContentDemoModuleScssNamespace.IContentDemoModuleScss;
};

export = ContentDemoModuleScssModule;
