// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ArticleProfileItemModuleScssNamespace {
    export interface IArticleProfileItemModuleScss {
        abstract: string;
        meta: string;
        profileItem: string;
        title: string;
        wrapImg: string;
    }
}

declare const ArticleProfileItemModuleScssModule: ArticleProfileItemModuleScssNamespace.IArticleProfileItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ArticleProfileItemModuleScssNamespace.IArticleProfileItemModuleScss;
};

export = ArticleProfileItemModuleScssModule;
