// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace BlogHeaderModuleScssNamespace {
    export interface IBlogHeaderModuleScss {
        header: string;
        headerMenu: string;
        left: string;
        logo: string;
        right: string;
        rightContent: string;
        title: string;
    }
}

declare const BlogHeaderModuleScssModule: BlogHeaderModuleScssNamespace.IBlogHeaderModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: BlogHeaderModuleScssNamespace.IBlogHeaderModuleScss;
};

export = BlogHeaderModuleScssModule;
