// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace BlogLayoutModuleScssNamespace {
    export interface IBlogLayoutModuleScss {
        layoutContent: string;
    }
}

declare const BlogLayoutModuleScssModule: BlogLayoutModuleScssNamespace.IBlogLayoutModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: BlogLayoutModuleScssNamespace.IBlogLayoutModuleScss;
};

export = BlogLayoutModuleScssModule;
